<a href="https://colab.research.google.com/github/kmk0909/2026-BDA/blob/main/code/06w_dataframe_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##6.1 pandas 개요

In [ ]:
import numpy as np
import pandas as pd

s = pd.Series([1,3,5,np.nan,6,8], name='first')
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [ ]:
s.name

'first'

In [ ]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
s.values

array([ 1.,  3.,  5., nan,  6.,  8.])

In [ ]:
s.shape

(6,)

In [ ]:
s.size

6

In [ ]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [ ]:
s[1]

np.float64(3.0)

In [ ]:
s[1:5]

1    3.0
2    5.0
3    NaN
4    6.0
Name: first, dtype: float64

In [ ]:
s.index = list('abcdef')
s

a     1.0
b    10.0
c     5.0
d     NaN
e     6.0
f     8.0
Name: first, dtype: float64

In [ ]:
print(s['b'], s['d'])

3.0 nan

In [ ]:
s['c':'e']

c    5.0
d    NaN
e    6.0
Name: first, dtype: float64

In [ ]:
s['b':'f']

b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
Name: first, dtype: float64

In [ ]:
s[0:3]

a    1.0
b    3.0
c    5.0
Name: first, dtype: float64

In [ ]:
s1 = s[1:4]
s1

b    10.0
c     5.0
d     NaN
Name: first, dtype: float64

In [ ]:
s1[0]

/tmp/ipykernel_976/643609873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]

np.float64(10.0)

In [ ]:
s1[0] = 10
s1

/tmp/ipykernel_976/3344545903.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  s1[0] = 10

b    10.0
c     5.0
d     NaN
Name: first, dtype: float64

In [ ]:
s

a    10.0
b    10.0
c     5.0
d     NaN
e     6.0
f     8.0
Name: first, dtype: float64

In [ ]:
s.index = np.arange(1, 7)
s

1    10.0
2    10.0
3     5.0
4     NaN
5     6.0
6     8.0
Name: first, dtype: float64

In [ ]:
s[1]

np.float64(10.0)

In [ ]:
s[0]

/tmp/ipykernel_976/243613605.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0]

np.float64(10.0)

In [ ]:
s[1:3]

b    10.0
c     5.0
Name: first, dtype: float64

##6.2 데이터프레임 생성

In [1]:
import pandas as pd
import numpy as np

dates = pd,pd.date_range("20260408", periods=6)
dates

(<module 'pandas' from '/usr/local/lib/python3.12/dist-packages/pandas/__init__.py'>,
 DatetimeIndex(['2026-04-08', '2026-04-09', '2026-04-10', '2026-04-11',
                '2026-04-12', '2026-04-13'],
               dtype='datetime64[ns]', freq='D'))

In [ ]:
dates = pd,pd.date_range("20260408", end="20260420")
dates

(<module 'pandas' from '/usr/local/lib/python3.12/dist-packages/pandas/__init__.py'>,
 DatetimeIndex(['2026-04-08', '2026-04-09', '2026-04-10', '2026-04-11',
                '2026-04-12', '2026-04-13', '2026-04-14', '2026-04-15',
                '2026-04-16', '2026-04-17', '2026-04-18', '2026-04-19',
                '2026-04-20'],
               dtype='datetime64[ns]', freq='D'))

In [ ]:
dates = pd.date_range("20260408", periods=3, freq='8D')
dates

DatetimeIndex(['2026-04-08', '2026-04-16', '2026-04-24'], dtype='datetime64[ns]', freq='8D')

In [ ]:
dates = pd.date_range("20260408", periods=3, freq='5h')
dates

DatetimeIndex(['2026-04-08 00:00:00', '2026-04-08 05:00:00',
               '2026-04-08 10:00:00'],
              dtype='datetime64[ns]', freq='5h')

In [ ]:
dates = pd.date_range("20260408", periods=3, freq='W')
dates

DatetimeIndex(['2026-04-12', '2026-04-19', '2026-04-26'], dtype='datetime64[ns]', freq='W-SUN')

In [ ]:
dates = pd.date_range("20260408", periods=3, freq='W-SAT')
dates

DatetimeIndex(['2026-04-11', '2026-04-18', '2026-04-25'], dtype='datetime64[ns]', freq='W-SAT')

In [ ]:
dates = pd.date_range("20260408", periods=3, freq='W-TUE')
dates

DatetimeIndex(['2026-04-14', '2026-04-21', '2026-04-28'], dtype='datetime64[ns]', freq='W-TUE')

In [ ]:
dates = pd.date_range("20260408", periods=3, freq='M')
dates

/tmp/ipykernel_976/2060573271.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range("20260408", periods=3, freq='M')

DatetimeIndex(['2026-04-30', '2026-05-31', '2026-06-30'], dtype='datetime64[ns]', freq='ME')

In [ ]:
dates = pd.date_range("20260408", periods=3, freq='ME')
dates

DatetimeIndex(['2026-04-30', '2026-05-31', '2026-06-30'], dtype='datetime64[ns]', freq='ME')

In [ ]:
dates = pd.date_range("20260408", periods=3, freq='MS')
dates

DatetimeIndex(['2026-05-01', '2026-06-01', '2026-07-01'], dtype='datetime64[ns]', freq='MS')

In [ ]:
dates = pd.date_range("20260408", periods=6)
dates

DatetimeIndex(['2026-04-08', '2026-04-09', '2026-04-10', '2026-04-11',
               '2026-04-12', '2026-04-13'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df

                   A         B         C         D
2026-04-08  0.178710  2.146187  0.359458  0.330704
2026-04-09  0.852971  0.014380 -0.198173 -1.733106
2026-04-10 -0.622089 -0.802810  0.419599 -1.717220
2026-04-11 -0.270623 -3.374918  0.169617  0.084692
2026-04-12  0.460936 -1.295006 -1.038776  2.106106
2026-04-13  0.605522  0.347373 -0.061035 -0.289190

##6.3 DataFrame의 다양한 참조

In [ ]:
import pandas as pd
pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈',],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
pf['중간']

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [ ]:
pf.중간

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [ ]:
pf['출석']

윤일형    18
강수희    20
홍소희    19
유한빈    20
신수빈    16
Name: 출석, dtype: int64

In [ ]:
ddf = pf[['출석']]
type(ddf)

pandas.core.frame.DataFrame

In [ ]:
pf.loc['강수희']

중간    18
기말    27
과제    10
출석    20
Name: 강수희, dtype: int64

In [ ]:
pf.loc[['강수희']]

     중간  기말  과제  출석
강수희  18  27  10  20

In [ ]:
pf.loc[['강수희', '신수빈']]

     중간  기말  과제  출석
강수희  18  27  10  20
신수빈  22  34   8  16

In [ ]:
pf[['기말', '출석', '중간']]

     기말  출석  중간
윤일형  35  18  25
강수희  27  20  18
홍소희  17  19  17
유한빈  22  20  12
신수빈  34  16  22

In [ ]:
pf[pf.기말 > 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
pf[['기말']]

     기말
윤일형  35
강수희  27
홍소희  17
유한빈  22
신수빈  34

In [ ]:
point = 20
pf.query('기말 > @point')

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
point = 20
pf.query(f'기말 > @point')

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
pf[(pf['출석'] >= 19) & (pf['기말'] >= 20)]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [ ]:
pf.loc['윤일형' : '유한빈']

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [ ]:
df = pf.loc['윤일형' : '유한빈']
type(df)

pandas.core.frame.DataFrame

In [ ]:
pf.loc[pf.중간 > 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [ ]:
pf.중간> 20

윤일형     True
강수희    False
홍소희    False
유한빈    False
신수빈     True
Name: 중간, dtype: bool

In [ ]:
pf.loc[(pf.중간 > 10) & (pf.과제 == 10)]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19

In [ ]:
pf.loc[pf.index[0]]

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [ ]:
pf.loc[[pf.index[0]]]

     중간  기말  과제  출석
윤일형  25  35   8  18

In [ ]:
pf.loc[pf.index[1:4]]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

##7.1 데이터프레임 정보와 조건 검색

In [3]:
import pandas as pd
df = pd.read_csv('2016년졸음운전.csv',
                 encoding='euc-kr', index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df.dtypes

사고(건)    int64
사망(명)    int64
부상(명)    int64
dtype: object

In [ ]:
df.dtypes.iloc[0]

dtype('int64')

In [ ]:
type(df.dtypes)

pandas.core.series.Series

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 2016년1월 to 2016년12월
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사고(건)   12 non-null     int64
 1   사망(명)   12 non-null     int64
 2   부상(명)   12 non-null     int64
dtypes: int64(3)
memory usage: 384.0+ bytes

In [ ]:
df.describe()

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [ ]:
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df.T

연월,2016년1월,2016년2월,2016년3월,2016년4월,2016년5월,2016년6월,2016년7월,2016년8월,2016년9월,2016년10월,2016년11월,2016년12월
사고(건),192,174,217,216,239,200,227,230,187,183,200,168
사망(명),5,6,7,7,13,12,9,7,13,10,5,4
부상(명),387,328,435,419,522,362,460,490,347,367,418,364

In [ ]:
df.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [ ]:
df.sum(axis=0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [ ]:
df.sum(axis=1)

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

In [ ]:
df.sum(axis=None)

/tmp/ipykernel_976/1369781367.py:1: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  df.sum(axis=None)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [ ]:
df.cumsum()

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [ ]:
df.cumsum(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [ ]:
df.cumsum(axis=1)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

In [5]:
from IPython.display import display_html
def display_side_by_side(*args):
    """여러 데이터프레임 비교가 쉽게 옆쪽으로 표시한다"""
    html_str=''
    for df in args:
        html_str += df.to_html() + ' '*4
    display_html(html_str.replace('table','table style="display:inline"'), raw=True)

In [7]:
display_side_by_side(df, df.cumsum(axis=1))

,사고(건),사망(명),부상(명)
연월,,,
2016년1월,192,5,387
2016년2월,174,6,328
2016년3월,217,7,435
2016년4월,216,7,419
2016년5월,239,13,522
2016년6월,200,12,362
2016년7월,227,9,460
2016년8월,230,7,490
2016년9월,187,13,347
2016년10월,183,10,367
2016년11월,200,5,418
2016년12월,168,4,364
,사고(건),사망(명),부상(명)
연월,,,
2016년1월,192,197,584
2016년2월,174,180,508
2016년3월,217,224,659
2016년4월,216,223,642
2016년5월,239,252,774
2016년6월,200,212,574
2016년7월,227,236,696
2016년8월,230,237,727
2016년9월,187,200,547
2016년10월,183,193,560
2016년11월,200,205,623
2016년12월,168,172,536

In [6]:
display_side_by_side(df, df.cumsum(axis=0))

,사고(건),사망(명),부상(명)
연월,,,
2016년1월,192,5,387
2016년2월,174,6,328
2016년3월,217,7,435
2016년4월,216,7,419
2016년5월,239,13,522
2016년6월,200,12,362
2016년7월,227,9,460
2016년8월,230,7,490
2016년9월,187,13,347
2016년10월,183,10,367
2016년11월,200,5,418
2016년12월,168,4,364
,사고(건),사망(명),부상(명)
연월,,,
2016년1월,192,5,387
2016년2월,366,11,715
2016년3월,583,18,1150
2016년4월,799,25,1569
2016년5월,1038,38,2091
2016년6월,1238,50,2453
2016년7월,1465,59,2913
2016년8월,1695,66,3403
2016년9월,1882,79,3750
2016년10월,2065,89,4117
2016년11월,2265,94,4535
2016년12월,2433,98,4899

In [ ]:
df.mean()

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [ ]:
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [ ]:
df.mean(axis=None)

np.float64(206.38888888888889)

In [ ]:
df.max()

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [8]:
display_side_by_side(df,df.mean(axis=1).to_frame())

In [9]:
display_side_by_side(df,df.max(axis=1).to_frame())

In [10]:
display_side_by_side(df.max().to_frame(),df.min().to_frame())

,0
사고(건),239
사망(명),13
부상(명),522
,0
사고(건),168
사망(명),4
부상(명),328

In [11]:
display_side_by_side(df.max(axis=0).to_frame(),df.min(axis=0).to_frame())

,0
사고(건),239
사망(명),13
부상(명),522
,0
사고(건),168
사망(명),4
부상(명),328

In [13]:
df2 =df.copy()
df2['재해자수'] = df[['사망(명)', '부상(명)']].sum(axis=1)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [14]:
display_side_by_side(df,df2)

In [16]:
df2.loc['총계']=df2.sum(axis=0)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368
총계         2433     98   4899  4997

In [17]:
df2>10

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    True  False   True  True
2016년2월    True  False   True  True
2016년3월    True  False   True  True
2016년4월    True  False   True  True
2016년5월    True   True   True  True
2016년6월    True   True   True  True
2016년7월    True  False   True  True
2016년8월    True  False   True  True
2016년9월    True   True   True  True
2016년10월   True  False   True  True
2016년11월   True  False   True  True
2016년12월   True  False   True  True
총계         True   True   True  True

In [18]:
df2[df2>10]

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192    NaN    387   392
2016년2월     174    NaN    328   334
2016년3월     217    NaN    435   442
2016년4월     216    NaN    419   426
2016년5월     239   13.0    522   535
2016년6월     200   12.0    362   374
2016년7월     227    NaN    460   469
2016년8월     230    NaN    490   497
2016년9월     187   13.0    347   360
2016년10월    183    NaN    367   377
2016년11월    200    NaN    418   423
2016년12월    168    NaN    364   368
총계         2433   98.0   4899  4997

In [19]:
df2[[True]*6+[False]*7]

         사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    192      5    387   392
2016년2월    174      6    328   334
2016년3월    217      7    435   442
2016년4월    216      7    419   426
2016년5월    239     13    522   535
2016년6월    200     12    362   374

In [20]:
df2['재해자수']>400

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월      True
2016년6월     False
2016년7월      True
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월     True
2016년12월    False
총계           True
Name: 재해자수, dtype: bool

In [21]:
df2['사망(명)']==7

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
총계          False
Name: 사망(명), dtype: bool

In [22]:
df[df['사망(명)'].isin([7,10])]

          사고(건)  사망(명)  부상(명)
연월
2016년3월     217      7    435
2016년4월     216      7    419
2016년8월     230      7    490
2016년10월    183     10    367

In [23]:
df[(df['사망(명)'].isin([7,10])) | (df['부상(명)']>350)]

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [24]:
df[df.index.str.contains('3')]

         사고(건)  사망(명)  부상(명)
연월
2016년3월    217      7    435

In [25]:
df3 = df.copy()
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [26]:
df = pd.DataFrame({
                   'A': range(1,6),
                   'B': range(6,-3, -2),
                   'C': range(10, 5, -1),
                   'D clmns': range(3, -2, -1),
                   'E': ['python', 'java', 'python', 'go', 'python']
                  })
df

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [27]:
df.query('A>B')

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [28]:
df[df.A>df.B]

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [29]:
df.query('A>0')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [30]:
df.query('E=="python"')

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [31]:
df.query('A == `D clmns`')

   A  B  C  D clmns     E
1  2  4  9        2  java

In [32]:
df[df.A == df["D clmns"]]

   A  B  C  D clmns     E
1  2  4  9        2  java

In [33]:
df.query('A>2&C<8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [34]:
df.query("E in ['python','go']")

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [35]:
num=3
df.query(f'B> {num}')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [36]:
s="E.str.contains('g')"
df.query(s)

   A  B  C  D clmns   E
3  4  0  7        0  go